### ISSUE TITLE
Error when using rspec-its

### ISSUE THREAD

**Issue by obfuscoder** [nviennot/rspec-console#19]
It seems rspec-its is not supported (at least with JRuby). Using the following dependencies and executing the specs (on the rails console within the test environment) of a file containing a spec with **its** leads to the following error:

    gem 'pry-rails'
    gem 'rails-env-switcher'
    gem 'rspec-console'
    gem 'rspec-rails', '~> 3.2'
    gem 'rspec-its'

Error:

    Loading test environment (Rails 3.2.21)
    [1] pry(main)> rspec
    NoMethodError: undefined method `its' for #<Class:0x6b0eba3a> from org/jruby/RubyBasicObject.java:1494:in `method_missing'

**Comment by nviennot** [comment]
You can fix this by requiring the rspec-its gem manually in your spec_helper:

Put in your Gemfile:

```ruby
gem 'rspec-its', :require => false
```

And in your `spec_helper.rb`:

```ruby
require 'rspec/its'
```
